# Generated by Django 5.1.7 on 2025-05-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rating_remove_feedback_rating_remove_product_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('TQ', 'Technique'), ('BK', 'Book'), ('FR', 'Furniture'), ('SP', 'Sport'), ('CN', 'Children'), ('DF', 'Default')], default='DF', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='count_items',
            field=models.IntegerField(default=10, verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='доступно?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=30, verbose_name='продукт'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='цена'),
        ),
    ]
