# Generated by Django 5.1.7 on 2025-04-02 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('shop', '0003_rating_remove_feedback_rating_remove_product_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('rating_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.rating')),
                ('user_detail', models.CharField(max_length=60, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_rating', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('shop.rating', models.Model),
        ),
    ]
